import {GOOGLE_ID, GOOGLE_SECRET, GITHUB_ID, GITHUB_SECRET} from './api';

const APP_REDIRECT_URL = 'http://localhost:3000/oauth';

export {
	GOOGLE_ID,
	GOOGLE_SECRET,
	GITHUB_ID,
	GITHUB_SECRET,
	APP_REDIRECT_URL
};