import {
	GOOGLE_ID,
	GOOGLE_SECRET,
	GITHUB_ID,
	GITHUB_SECRET,
	FACEBOOK_ID,
	FACEBOOK_SECRET,
	GMAPS_API
} from './api';

const APP_REDIRECT_URL = 'https://localhost:3000/oauth';

export {
	GOOGLE_ID,
	GOOGLE_SECRET,
	GITHUB_ID,
	GITHUB_SECRET,
	FACEBOOK_ID,
	FACEBOOK_SECRET,
	APP_REDIRECT_URL,
	GMAPS_API
};